/*
EX360 implementation notes (source-level only):
- Feedback360 (MIT): survey-cycle / reviewer / self-rating workflow concepts. https://github.com/nashjain/feedback360
- Thermondo ThreeSixty (Apache-2.0): same question set across rater groups and reflection/action orientation. https://github.com/thermondo/threesixty
- Vital Aspect (MIT): feedback -> insight -> action/check-in workflow. https://github.com/geeknees/vital_aspect
No third-party source code is copied verbatim in this file.
*/
const DIMENSIONS=[
 {id:'strategy',name:'الاتجاه والاستراتيجية',short:'الاستراتيجية',actions:['حدد 3 أولويات استراتيجية فقط للربع القادم واربط كل أولوية بمالك ومورد.','راجع توزيع الموارد وتأكد أن الإنفاق والوقت يعكسان الأولويات الفعلية.']},
 {id:'execution',name:'التنفيذ والنتائج',short:'التنفيذ',actions:['أنشئ إيقاع متابعة أسبوعي للمبادرات الحرجة مع قرار واضح لكل انحراف.','اربط كل مبادرة استراتيجية بمؤشر نتيجة واحد ومسؤول واحد.']},
 {id:'team',name:'قيادة الفريق التنفيذي',short:'الفريق',actions:['انقل 3 فئات قرارات من مكتب الرئيس إلى ملاك تنفيذيين بصلاحيات واضحة.','حدد أين يعتمد الفريق عليك بشكل زائد ثم أعد توزيع القرار والمساءلة.']},
 {id:'board',name:'المجلس والحوكمة',short:'المجلس',actions:['أعد تصميم جدول أعمال المجلس ليبدأ بالقضايا الاستراتيجية والقرارات المطلوبة.','اتفق مع رئيس المجلس على 3 توقعات واضحة لجودة المعلومات والتفاعل بين الاجتماعات.']},
 {id:'stakeholders',name:'أصحاب المصلحة',short:'الأطراف',actions:['حدد أهم 5 أصحاب مصلحة وخطة تواصل وهدف محدد لكل علاقة.','حوّل العلاقات الخارجية من نشاط تواصلي إلى أجندة نتائج مرتبطة بالاستراتيجية.']},
 {id:'personal',name:'فاعلية الرئيس التنفيذي',short:'الفاعلية',actions:['راجع تقويم آخر 4 أسابيع واحذف أو فوّض الأنشطة التي لا تتطلب دور الرئيس التنفيذي.','احجز وقتا أسبوعيا ثابتا للقرارات الاستراتيجية والتفكير غير التشغيلي.']}
];
const QUESTIONS=[
 ['strategy','أستطيع تحديد 3 أولويات استراتيجية واضحة تقود قراراتنا الحالية.'],['strategy','توزيع الموارد لدينا يعكس الأولويات الاستراتيجية فعلياً.'],['strategy','نعرف بوضوح ما الذي لن نقوم به خلال الفترة الحالية.'],
 ['execution','لكل مبادرة استراتيجية مسؤول واحد ومؤشر نتيجة واضح.'],['execution','الانحرافات المهمة تتحول بسرعة إلى قرار وإجراء.'],['execution','اجتماعات المتابعة تركز على النتائج والعوائق أكثر من استعراض النشاط.'],
 ['team','أعضاء الفريق التنفيذي يملكون صلاحيات فعلية ضمن نطاقاتهم.'],['team','الفريق يستطيع مناقشة قراراتي وتحديها مهنياً قبل اعتمادها.'],['team','المنظمة لا تعتمد عليّ شخصياً في معظم القرارات التشغيلية المهمة.'],
 ['board','المجلس يناقش القضايا الاستراتيجية قبل التفاصيل التشغيلية.'],['board','المعلومات المرفوعة للمجلس موجزة وتوضح القرار المطلوب والمخاطر.'],['board','العلاقة مع رئيس المجلس واضحة في الأدوار والتوقعات والتواصل.'],
 ['stakeholders','لدينا خريطة واضحة لأصحاب المصلحة الأكثر تأثيراً على الاستراتيجية.'],['stakeholders','أخصص وقتاً كافياً للعملاء والشركاء والجهات المؤثرة.'],['stakeholders','العلاقات الخارجية مرتبطة بأهداف ونتائج وليست نشاطاً منفصلاً.'],
 ['personal','استخدام وقتي يعكس أولوياتي المعلنة كرئيس تنفيذي.'],['personal','أفصل بين القرارات التي تتطلبني والقرارات التي يجب تفويضها.'],['personal','لدي مساحة منتظمة للتفكير والمراجعة بعيداً عن ضغط التشغيل.']
].map((q,i)=>({id:'q'+(i+1),dim:q[0],text:q[1]}));
const ROLES={self:'الرئيس التنفيذي',board:'مجلس الإدارة',exec:'الفريق التنفيذي'};
const STORAGE='ex360_demo_v2';
let state=loadState();
let currentRole='self';
function defaultState(){return{ratings:{self:{},board:{},exec:{}},completed:{self:false,board:false,exec:false},plan:[],updatedAt:null}}
function loadState(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch(e){return defaultState()}}
function persist(){state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(state));updateMetrics()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.classList.remove('show'),2200)}
function renderQuestions(){const root=document.getElementById('questions');root.innerHTML=QUESTIONS.map(q=>{const d=DIMENSIONS.find(x=>x.id===q.dim);return `<div class="qcard"><div class="dim">${d.name}</div><div class="statement">${q.text}</div><div class="scale">${[1,2,3,4,5].map(v=>`<input id="${currentRole}-${q.id}-${v}" type="radio" name="${q.id}" value="${v}" ${state.ratings[currentRole]?.[q.id]==v?'checked':''}><label for="${currentRole}-${q.id}-${v}">${v}</label>`).join('')}</div><div class="legend"><span>ضعيف</span><span>قوي</span></div></div>`}).join('');root.querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>{state.ratings[currentRole][i.name]=Number(i.value);persist();updateProgress()}));updateProgress()}
function updateProgress(){const n=Object.keys(state.ratings[currentRole]||{}).length;document.getElementById('progressBar').style.width=(n/QUESTIONS.length*100)+'%';document.getElementById('progressText').textContent=`${n} من ${QUESTIONS.length}`;document.getElementById('scanMetric').innerHTML=`<strong>${Math.round(Object.keys(state.ratings.self||{}).length/QUESTIONS.length*100)}%</strong> مكتمل`}
function setRole(role,btn){currentRole=role;document.querySelectorAll('.role-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));renderQuestions();if(btn)btn.scrollIntoView({block:'nearest'})}
function saveCurrent(){persist();toast('تم حفظ التقييم على هذا الجهاز')}
function clearRole(){if(!confirm('هل تريد مسح إجابات '+ROLES[currentRole]+'؟'))return;state.ratings[currentRole]={};state.completed[currentRole]=false;persist();renderQuestions();renderResults();toast('تمت إعادة التقييم')}
function completeAssessment(){const n=Object.keys(state.ratings[currentRole]||{}).length;if(n<QUESTIONS.length){toast(`تبقى ${QUESTIONS.length-n} عبارة`);return}state.completed[currentRole]=true;persist();renderResults();generatePlan(false);openPane('resultsPane');toast('اكتمل تقييم '+ROLES[currentRole])}
function dimensionScores(role){const ratings=state.ratings[role]||{};return Object.fromEntries(DIMENSIONS.map(d=>{const qs=QUESTIONS.filter(q=>q.dim===d.id);const vals=qs.map(q=>ratings[q.id]).filter(Boolean);return[d.id,vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null]}))}
function completedRoles(){return Object.keys(ROLES).filter(r=>state.completed[r])}
function overall(role){const s=dimensionScores(role);const vals=Object.values(s).filter(v=>v!=null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function avgDimension(dim){const vals=completedRoles().map(r=>dimensionScores(r)[dim]).filter(v=>v!=null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function renderResults(){const root=document.getElementById('resultsContent');const roles=completedRoles();if(!roles.length){root.innerHTML='<div class="empty">أكمل تقييماً واحداً على الأقل لعرض النتائج.</div>';return}const allDims=DIMENSIONS.map(d=>({d,score:avgDimension(d.id)})).filter(x=>x.score!=null);const sorted=[...allDims].sort((a,b)=>a.score-b.score);const lowest=sorted[0],highest=sorted[sorted.length-1];let gap=null;if(state.completed.self){const self=dimensionScores('self');const otherRoles=roles.filter(r=>r!=='self');if(otherRoles.length){gap=DIMENSIONS.map(d=>{const o=otherRoles.map(r=>dimensionScores(r)[d.id]).filter(v=>v!=null);const oa=o.length?o.reduce((a,b)=>a+b,0)/o.length:null;return oa==null?null:{d,self:self[d.id],others:oa,gap:Math.abs(self[d.id]-oa)}}).filter(Boolean).sort((a,b)=>b.gap-a.gap)[0]}}
const overallAvg=roles.map(overall).filter(v=>v!=null).reduce((a,b)=>a+b,0)/roles.length;
root.innerHTML=`<div class="result-grid"><div class="result-card"><div class="score-big">${Math.round(overallAvg*20)}<small>/100</small></div><div class="insights"><div class="insight"><strong>أقوى مجال</strong><span>${highest.d.name} — ${highest.score.toFixed(1)}/5</span></div><div class="insight"><strong>الأولوية الأولى</strong><span>${lowest.d.name} — ${lowest.score.toFixed(1)}/5</span></div>${gap?`<div class="insight"><strong>أكبر فجوة إدراك</strong><span>${gap.d.name} — فارق ${gap.gap.toFixed(1)} نقطة</span></div>`:''}<div class="insight"><strong>الخطوة التالية</strong><span>${lowest.d.actions[0]}</span></div></div></div><div class="result-card"><div class="chart-wrap">${radarSvg()}</div><div class="chart-legend">${roles.map(r=>`<span class="legend-item"><i class="dot" style="background:${roleColor(r)}"></i>${ROLES[r]}</span>`).join('')}</div></div></div>`}
function roleColor(r){return r==='self'?'#1f2b39':r==='board'?'#a98954':'#768392'}
function radarSvg(){const roles=completedRoles(),cx=220,cy=185,R=125,N=DIMENSIONS.length;const pt=(i,val)=>{const a=-Math.PI/2+i*2*Math.PI/N;const rr=R*(val/5);return[cx+Math.cos(a)*rr,cy+Math.sin(a)*rr]};let svg=`<svg viewBox="0 0 440 380" role="img" aria-label="مخطط نتائج EX360">`;for(let l=1;l<=5;l++){svg+=`<polygon points="${DIMENSIONS.map((_,i)=>pt(i,l).join(',')).join(' ')}" fill="none" stroke="#e5ddd1" stroke-width="1"/>`}DIMENSIONS.forEach((d,i)=>{const p=pt(i,5);svg+=`<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}" stroke="#e5ddd1"/>`;const lp=pt(i,6.05);svg+=`<text x="${lp[0]}" y="${lp[1]}" text-anchor="middle" dominant-baseline="middle" font-size="11" fill="#68717c">${d.short}</text>`});roles.forEach(r=>{const s=dimensionScores(r);const points=DIMENSIONS.map((d,i)=>pt(i,s[d.id]||0).join(',')).join(' ');svg+=`<polygon points="${points}" fill="${roleColor(r)}22" stroke="${roleColor(r)}" stroke-width="2.5"/>`});return svg+'</svg>'}
function generatePlan(force){const roles=completedRoles();if(!roles.length){document.getElementById('planList').innerHTML='<div class="empty">أكمل التقييم أولاً ثم سيتم اقتراح خطة 90 يوم.</div>';return}if(state.plan.length && !force){renderPlan();return}const lowest=DIMENSIONS.map(d=>({d,score:avgDimension(d.id)})).filter(x=>x.score!=null).sort((a,b)=>a.score-b.score).slice(0,3);const dates=[30,60,90];state.plan=lowest.map((x,i)=>({dim:x.d.id,title:x.d.name,action:x.d.actions[0],metric:'مؤشر نجاح قابل للقياس',days:dates[i],status:'لم يبدأ'}));persist();renderPlan()}
function renderPlan(){const root=document.getElementById('planList');if(!state.plan.length){generatePlan(false);return}root.innerHTML=state.plan.map((p,i)=>`<div class="plan-item"><div class="plan-top"><div><h4>${i+1}. ${p.title}</h4><p>أولوية مستخرجة من نتائج EX360.</p></div><span class="status">${p.days} يوم</span></div><div class="plan-fields"><input data-i="${i}" data-k="action" value="${esc(p.action)}" aria-label="الإجراء"><input data-i="${i}" data-k="metric" value="${esc(p.metric)}" aria-label="مؤشر النجاح"><select data-i="${i}" data-k="status"><option ${p.status==='لم يبدأ'?'selected':''}>لم يبدأ</option><option ${p.status==='قيد التنفيذ'?'selected':''}>قيد التنفيذ</option><option ${p.status==='مكتمل'?'selected':''}>مكتمل</option></select></div></div>`).join('')}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function savePlan(){document.querySelectorAll('#planList [data-i]').forEach(el=>{state.plan[Number(el.dataset.i)][el.dataset.k]=el.value});persist();toast('تم حفظ خطة 90 يوم')}
function updateMetrics(){const roles=completedRoles();document.getElementById('raterMetric').innerHTML=`<strong>${roles.length}/3</strong> وجهات مكتملة`;document.getElementById('planMetric').innerHTML=`<strong>${state.plan.length}</strong> أولويات`;if(document.getElementById('scanMetric'))document.getElementById('scanMetric').innerHTML=`<strong>${Math.round(Object.keys(state.ratings.self||{}).length/QUESTIONS.length*100)}%</strong> مكتمل`}
function openPane(id,btn){document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.workspace-nav button').forEach(b=>b.classList.toggle('active',b.dataset.pane===id));if(id==='resultsPane')renderResults();if(id==='planPane')generatePlan(false);document.querySelector('#platform').scrollIntoView({behavior:'smooth',block:'start'})}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),dimensions:DIMENSIONS.map(({actions,...d})=>d),questions:QUESTIONS,state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='EX360-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('تم تجهيز ملف البيانات')}
function resetAll(){if(!confirm('سيتم مسح جميع تقييمات وخطة EX360 المحفوظة على هذا الجهاز. متابعة؟'))return;localStorage.removeItem(STORAGE);state=defaultState();currentRole='self';renderQuestions();renderResults();renderPlan();updateMetrics();toast('تم مسح البيانات')}
renderQuestions();renderResults();generatePlan(false);updateMetrics();