from playwright.sync_api import sync_playwright, expect
import json,pathlib,threading,http.server,functools
site=pathlib.Path(__file__).resolve().parents[1]
root=site/'test-artifacts'
root.mkdir(exist_ok=True)
server=http.server.ThreadingHTTPServer(('127.0.0.1',8765),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(site)))
threading.Thread(target=server.serve_forever,daemon=True).start()
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1440,'height':1060},accept_downloads=True)
 # Keep this test independent from external asset availability.
 context.route('https://**/*',lambda route:route.abort())
 page=context.new_page();errors=[]
 page.on('pageerror',lambda error:errors.append(str(error)))
 page.goto('http://127.0.0.1:8765/',wait_until='networkidle')
 page.screenshot(path=str(root/'desktop.png'),full_page=True)
 expect(page.locator('.stat b').first).to_have_text('8')
 page.locator('[data-action="add-record"]').first.click()
 page.locator('[name="name"]').fill('سجل اختبار <script>alert(1)</script>')
 page.locator('[name="offers"]').fill('برمجة منصة للمطاعم')
 page.locator('#recordForm button[type="submit"]').click()
 page.wait_for_selector('#dialog',state='hidden')
 expect(page.locator('.stat b').first).to_have_text('9')
 page.locator('a[href="#knowledge"]').click()
 page.locator('#knowledgeSearch').fill('سجل اختبار')
 expect(page.locator('#knowledgeResults article')).to_have_count(1)
 assert 'script' in page.locator('#knowledgeResults article').inner_text()
 page.locator('a[href="#opportunities"]').click()
 page.locator('[data-action="view-match"]').first.click()
 page.locator('[data-action="create-intro"]').click()
 page.locator('[name="stage"]').select_option('introduced')
 page.locator('#introForm button[type="submit"]').click()
 expect(page.locator('.form-error')).to_contain_text('وثق موافقة')
 page.locator('[name="consentA"]').check();page.locator('[name="consentB"]').check()
 page.locator('[name="consentEvidence"]').fill('اتصال افتراضي بالطرفين بتاريخ اليوم')
 page.locator('#introForm button[type="submit"]').click()
 page.wait_for_selector('#dialog',state='hidden')
 page.locator('a[href="#intros"]').click()
 expect(page.locator('#main')).to_contain_text('تم التعارف')
 # Encrypted workspace must start empty, without copying demo records.
 page.locator('#workspaceBtn').click()
 page.locator('[name="password"]').fill('Test strong password 2026!')
 page.locator('[name="confirm"]').fill('Test strong password 2026!')
 page.locator('[name="understood"]').check()
 page.locator('#vaultForm button[type="submit"]').click()
 page.wait_for_selector('#dialog',state='hidden')
 expect(page.locator('.stat b').first).to_have_text('0')
 page.locator('[data-action="add-record"]').first.click()
 page.locator('[name="name"]').fill('PRIVATE_TEST_NAME')
 page.locator('[name="offers"]').fill('تصميم وتطوير منصات')
 page.locator('#recordForm button[type="submit"]').click()
 page.wait_for_selector('#dialog',state='hidden')
 stored=page.evaluate('JSON.stringify(localStorage)')
 assert 'PRIVATE_TEST_NAME' not in stored
 with page.expect_download() as info:page.locator('[data-action="backup"]').first.click()
 download=info.value;download.save_as(str(root/'test.kbvault'))
 assert 'PRIVATE_TEST_NAME' not in (root/'test.kbvault').read_text()
 page.reload(wait_until='networkidle')
 assert 'PRIVATE_TEST_NAME' not in page.locator('body').inner_text()
 page.locator('#workspaceBtn').click()
 page.locator('[name="password"]').fill('wrong password 2026!')
 page.locator('#vaultForm button[type="submit"]').click()
 expect(page.locator('.form-error')).not_to_have_text('')
 page.locator('[name="password"]').fill('Test strong password 2026!')
 page.locator('#vaultForm button[type="submit"]').click()
 page.wait_for_selector('#dialog',state='hidden')
 expect(page.locator('.stat b').first).to_have_text('1')
 page.locator('a[href="#knowledge"]').click()
 expect(page.locator('#main')).to_contain_text('PRIVATE_TEST_NAME')
 page.locator('#workspaceBtn').click();page.wait_for_selector('[data-action="demo"]')
 page.locator('[data-action="demo"]').first.click()
 # Overflow checks at common phone and desktop widths.
 results=[]
 for width in [320,375,390,768,1440]:
  page.set_viewport_size({'width':width,'height':900});page.goto('http://127.0.0.1:8765/#home')
  if page.locator('[data-action="demo"]').count():page.locator('[data-action="demo"]').first.click()
  for target in ['home','knowledge','opportunities','intros','tasks','settings']:
   if target=='settings':page.evaluate("document.querySelector('[data-action=settings]').click()")
   else:page.evaluate(f"location.hash='{target}'")
   page.wait_for_timeout(70)
   metrics=page.evaluate('({width:innerWidth,scroll:document.documentElement.scrollWidth})')
   assert metrics['scroll']<=width+1,(width,target,metrics)
   results.append({'width':width,'page':target,'overflow':False})
  if width==390:
   page.evaluate("location.hash='home'");page.wait_for_timeout(100)
   page.screenshot(path=str(root/'mobile.png'),full_page=True)
 assert errors==[],errors
 (root/'e2e-results.json').write_text(json.dumps({'passed':True,'page_errors':errors,'responsive_checks':results,'flows':['demo CRUD and escaped text','search','two-party consent gate','intro progression','empty private vault','encrypted save','encrypted export','locked reload','incorrect password','correct unlock']},ensure_ascii=False,indent=2))
 print('E2E PASS:',len(results),'responsive checks; no page errors')
 browser.close()
