import {VISIBILITY,VERIFICATION,STAGES,CATEGORIES,uid,day,emptyState,demoState,validateRecord,recordMatches,findMatches,canAdvance,recordsFromCSV} from './core.js';
import * as vault from './vault.js';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',knowledge:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 7h8M8 11h8M8 15h5"/>',opportunities:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>',intros:'<circle cx="7" cy="7" r="3"/><circle cx="17" cy="7" r="3"/><path d="M2 20v-3a5 5 0 0 1 9-3m2 0a5 5 0 0 1 9 3v3M8 18h8m-2-2 2 2-2 2"/>',tasks:'<rect x="4" y="4" width="16" height="17" rx="3"/><path d="M8 2v4m8-4v4M8 13l3 3 5-6"/>'};
const labels={home:'الرئيسية',knowledge:'بنك المعرفة',opportunities:'فرص التكامل',intros:'طلبات التعارف',tasks:'المتابعة'};
let mode=vault.exists()?'locked':'demo';
let state=mode==='demo'?demoState():emptyState();
let page=Object.hasOwn(labels,location.hash.slice(1))?location.hash.slice(1):'home';
let q='',sectorFilter='',visibilityFilter='',oppTab='suggested',taskTab='open';
let mutationQueue=Promise.resolve(),pending=0,lastActivity=Date.now(),importDraft=[];
function icon(name){return `<span class="nav-glyph"><svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]??''}</svg></span>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function fmt(date){if(!date)return 'موعد يحدد لاحقا';const d=new Date(date+'T12:00:00');if(Number.isNaN(d.getTime()))return 'تاريخ يحتاج مراجعة';return d.toLocaleDateString('ar-SA-u-ca-gregory-nu-latn',{day:'numeric',month:'short',year:'numeric'});}
function pill(text,type=''){return `<span class="pill ${type}">${esc(text)}</span>`;}
function options(map,value){return Object.entries(map).map(([k,v])=>`<option value="${esc(k)}" ${value===k?'selected':''}>${esc(v)}</option>`).join('');}
function person(id){return state.records.find(r=>r.id===id);}
function matches(){return findMatches(state.records);}
function savedMatch(id){const current=matches().find(x=>x.id===id);if(current)return current;const saved=state.opportunities.find(x=>x.id===id);return saved?{...saved,stale:true,reasons:['تغيرت المعلومات المسجلة. راجع التكامل من جديد قبل متابعة التعارف.'],checks:['مراجعة احتياج الطرف الأول وقدرة الطرف الثاني.','مراجعة الإذن وموافقة الأطراف.']}:null;}
function log(draft,message){draft.activity.unshift({id:uid(),message,at:new Date().toISOString()});draft.activity=draft.activity.slice(0,150);}
async function change(mutator,message){pending++;const operation=mutationQueue.catch(()=>{}).then(async()=>{if(mode==='locked')throw Error('افتح المساحة أولا.');const draft=structuredClone(state);mutator(draft);log(draft,message);$('#saveState').textContent=mode==='private'?'جار الحفظ…':'مساحة تجربة';if(mode==='private')await vault.save(draft);state=draft;render();toast(mode==='demo'?`${message} في التجربة.`:message);});mutationQueue=operation;try{await operation;}catch(e){$('#saveState').textContent='تعذر الحفظ';throw e;}finally{pending--;}}
function go(name){page=name;q='';if(Object.hasOwn(labels,name)){location.hash=name;}render();$('#sidebar').classList.remove('open');$('[data-action="menu"]').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'smooth'});}
function renderShell(){const counts={knowledge:state.records.length,opportunities:state.opportunities.length,intros:state.intros.length,tasks:state.tasks.filter(t=>!t.done).length};$('#nav').innerHTML=Object.entries(labels).map(([key,text])=>`<a class="nav-item ${page===key?'active':''}" href="#${key}" ${page===key?'aria-current="page"':''}>${icon(key)}${text}${counts[key]?`<span class="count">${counts[key]}</span>`:''}</a>`).join('');$('#workspaceName').textContent=mode==='demo'?'دائرة التجربة':'مساحتي الخاصة';$('#workspaceType').textContent=mode==='demo'?'بيانات افتراضية':mode==='locked'?'المساحة مقفلة':'حفظ مشفر في هذا المتصفح';$('#workspaceBtn').textContent=mode==='private'?'قفل المساحة':'مساحتي الخاصة';$('#saveState').textContent=mode==='private'?'محفوظ في هذا المتصفح':mode==='locked'?'المساحة مقفلة':'مساحة تجربة';$('#modeBanner').className='mode-banner'+(mode==='private'?' private':'');$('#modeBanner').innerHTML=mode==='demo'?'<span><strong>مساحة تجربة.</strong> الأسماء والفرص افتراضية. تنتهي تغييرات التجربة عند إعادة تحميل الصفحة.</span><button class="text-btn" data-action="workspace">افتح مساحتك ←</button>':mode==='private'?'<span><strong>مساحتك الخاصة.</strong> البيانات محفوظة مشفرة في هذا المتصفح فقط. احتفظ بنسخة احتياطية.</span><button class="text-btn" data-action="backup">نسخة احتياطية ↓</button>':'<span>بياناتك محفوظة مشفرة. افتح المساحة بكلمة المرور للوصول إليها.</span><button class="text-btn" data-action="demo">جولة تجريبية ←</button>';}
function render(){renderShell();if(mode==='locked'){renderLocked();return;}const fn={home:renderHome,knowledge:renderKnowledge,opportunities:renderOpportunities,intros:renderIntros,tasks:renderTasks,settings:renderSettings}[page]||renderHome;fn();}
function empty(title,text,action='add-record',button='إضافة معرفة'){return `<div class="empty"><div class="symbol" aria-hidden="true">◇</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${action?`<button class="btn" data-action="${action}">${esc(button)}</button>`:''}</div>`;}
function pageHead(title,description,buttons=''){return `<div class="page-head"><div><h1>${title}</h1><p>${description}</p></div>${buttons?`<div class="actions">${buttons}</div>`:''}</div>`;}
function opportunityCard(match){const a=person(match.fromId),b=person(match.toId);if(!a||!b)return '';const saved=state.opportunities.some(x=>x.id===match.id);return `<article class="card"><div class="card-top">${pill(saved?'فرصة محفوظة':'ترشيح أولي',saved?'green':'copper')}${pill(match.stale?'تحديث مطلوب':CATEGORIES[match.category]||'تعاون',match.stale?'red':'gray')}</div><h3>${esc(match.title)}</h3><div class="pair-row"><div class="pair-person"><small>يبحث عن</small><strong>${esc(a.name)}</strong><small>${esc(a.city)}</small></div><span class="pair-arrow" aria-hidden="true">←</span><div class="pair-person"><small>يقدم القدرة</small><strong>${esc(b.name)}</strong><small>${esc(b.city)}</small></div></div><p>${esc(match.reasons?.[0]||'راجع الاحتياج والقدرة قبل التعارف.')}</p><div class="card-bottom"><span>عبر ${esc(a.connector||'صاحب العلاقة')} و${esc(b.connector||'صاحب العلاقة')}</span><button class="btn secondary" data-action="view-match" data-id="${esc(match.id)}">راجع الفرصة ←</button></div></article>`;}
function taskPreview(task){const d=new Date(task.due+'T12:00:00');return `<div class="next-item"><div class="date-box">${Number.isNaN(d.getTime())?'·':d.getDate()}<small>${Number.isNaN(d.getTime())?'':esc(d.toLocaleDateString('ar-SA-u-ca-gregory-nu-latn',{month:'short'}))}</small></div><div><h3>${esc(task.title)}</h3><p>${esc(task.owner||'أنا')} · ${task.due&&task.due<day()?'متأخرة':fmt(task.due)}</p></div><button class="check-btn" data-action="toggle-task" data-id="${esc(task.id)}" aria-label="إنجاز ${esc(task.title)}">✓</button></div>`;}
function renderHome(){const list=matches(),tasks=state.tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,3),stale=state.records.filter(r=>r.reviewDate&&r.reviewDate<day()).length;$('#main').innerHTML=`<section class="hero"><div><span class="ey">بنك العلاقات والفرص</span><h1>معرفة تجمعنا.<br><span>وفرص تكملنا.</span></h1><p>سجل قدرات من تعرف، وما يبحثون عنه. واكتشف أين يمكن أن تبدأ فرصة تجمعهم.</p><div class="actions"><button class="btn copper" data-action="add-record">＋ إضافة معرفة</button><button class="btn secondary" data-action="discover">اكتشف فرص التكامل ←</button></div></div><div class="hero-link"><small>${mode==='demo'?'مثال على التكامل داخل الشبكة':'الفكرة تبدأ من معلومتين'}</small><div class="hero-pair"><div><div class="round" aria-hidden="true">◇</div><b>قدرة متاحة</b><small>شخص يستطيع أن يقدم</small></div><span aria-hidden="true">←</span><div><div class="round" aria-hidden="true">○</div><b>احتياج قائم</b><small>وآخر يبحث عنها</small></div></div><div class="hero-result">تعارف مناسب، ثم خطوة عملية</div></div></section><div class="stats">${[[state.records.length,'أشخاص وجهات','◇'],[list.length,'ترشيحات للمراجعة','✧'],[state.intros.length,'طلبات تعارف','↔'],[state.tasks.filter(t=>!t.done).length,'متابعات مفتوحة','✓']].map(([n,t,i])=>`<div class="stat"><div><b>${n}</b><span>${t}</span></div><div class="stat-icon" aria-hidden="true">${i}</div></div>`).join('')}</div><div class="dashboard-grid"><section><div class="section-head"><div><h2>فرص تستحق النظر</h2><p>مطابقة أولية بين القدرات والاحتياجات المسجلة</p></div><button class="text-btn" data-action="discover">كل الفرص ←</button></div>${list.length?list.slice(0,2).map(opportunityCard).join(''):empty('ابدأ بمعرفة مفيدة','أضف شخصين أو جهتين مع قدرة لدى أحدهما واحتياج لدى الآخر.')}</section><section><div class="section-head"><h2>الخطوة القادمة</h2><button class="text-btn" data-action="add-task">＋ متابعة</button></div><div class="card">${tasks.length?tasks.map(taskPreview).join(''):'<p>رتب موعدا لتأكيد معلومة، أو لمتابعة تعارف.</p>'}</div><div class="insight"><span class="ey">جودة المعرفة</span><h3>${stale?`${stale} سجل يحتاج تحديثا`:'كل معلومة لها مصدر'}</h3><p>${stale?'راجع الاحتياجات القديمة قبل البدء بأي تعارف.':'احتفظ بمصدر المعلومة وتاريخها، وميز ما تأكدت منه عما يحتاج مراجعة.'}</p><button class="text-btn" data-action="knowledge">راجع بنك المعرفة ←</button></div><div class="insight"><span class="ey">التعارف بموافقة أصحابه</span><p>النسخة الحالية تنظم المراجعة والمتابعة. توثيق الموافقة يتم بعد حصولك عليها خارج المنصة.</p></div></section></div>`;}
function renderKnowledge(){const sectors=[...new Set(state.records.map(r=>r.sector).filter(Boolean))].sort();$('#main').innerHTML=pageHead('بنك المعرفة','من تعرف؟ ماذا يقدم؟ وما الذي يبحث عنه؟','<button class="btn" data-action="add-record">＋ إضافة معرفة</button><button class="btn secondary" data-action="import-csv">استيراد CSV</button>')+`<div class="search-bar"><label class="search-wrap"><span aria-hidden="true">⌕</span><span class="visually-hidden">ابحث في المعرفة</span><input id="knowledgeSearch" type="search" autocomplete="off" value="${esc(q)}" placeholder="ابحث باسم، أو قدرة، أو احتياج…"></label><label class="visually-hidden" for="sectorFilter">القطاع</label><select id="sectorFilter"><option value="">كل القطاعات</option>${sectors.map(x=>`<option ${sectorFilter===x?'selected':''}>${esc(x)}</option>`).join('')}</select><label class="visually-hidden" for="visibilityFilter">إذن المشاركة المقترح</label><select id="visibilityFilter"><option value="">كل الأذونات</option>${options(VISIBILITY,visibilityFilter)}</select></div><div id="knowledgeResults"></div>`;renderKnowledgeResults();}
function renderKnowledgeResults(){const list=state.records.filter(r=>recordMatches(r,q)&&(!sectorFilter||r.sector===sectorFilter)&&(!visibilityFilter||r.visibility===visibilityFilter));$('#knowledgeResults').innerHTML=`<p class="results-info">${list.length} سجل · البحث يشمل المعلومات المضافة إلى مساحتك.</p>`+(list.length?`<div class="knowledge-grid">${list.map(r=>`<article class="card"><div class="card-top"><div class="person-head"><div class="avatar" aria-hidden="true">${esc(r.name.slice(0,1))}</div><div><h3>${esc(r.name)}</h3><small>${esc([r.role,r.city].filter(Boolean).join(' · '))}</small></div></div>${pill(r.reviewDate&&r.reviewDate<day()?'يحتاج تحديثا':VERIFICATION[r.verification],r.reviewDate&&r.reviewDate<day()?'red':r.verification==='confirmed'?'green':'copper')}</div><div class="capability"><span>يقدم</span><div>${esc(r.offers||'تضاف لاحقا')}</div></div><div class="capability"><span>يبحث عن</span><div>${esc(r.needs||'يضاف لاحقا')}</div></div><div class="meta-row">${pill(VISIBILITY[r.visibility],'gray')}<span>عبر ${esc(r.connector||'صاحب العلاقة')}</span></div><div class="card-bottom"><span>المصدر: ${esc(r.source||'يحتاج توثيق')} · ${fmt(r.sourceDate)}</span><button class="btn secondary" data-action="view-record" data-id="${esc(r.id)}">فتح الملف ←</button></div></article>`).join('')}</div>`:empty(state.records.length?'وسع نطاق البحث':'أول معرفة في البنك',state.records.length?'جرب اسم الشخص أو قدرته أو احتياجه.':'ابدأ بشخص تعرف ماذا يقدم أو عما يبحث.'));}
function renderOpportunities(){const list=oppTab==='saved'?state.opportunities.map(x=>savedMatch(x.id)).filter(Boolean):matches();$('#main').innerHTML=pageHead('فرص التكامل','ترشيحات قابلة للمراجعة، وليست وعودا بنتائج أو أرباح.','<button class="btn" data-action="refresh-matches">تحديث الترشيحات ↻</button>')+`<div class="tab-chips"><button class="chip ${oppTab==='suggested'?'active':''}" data-action="opp-tab" data-tab="suggested">الترشيحات · ${matches().length}</button><button class="chip ${oppTab==='saved'?'active':''}" data-action="opp-tab" data-tab="saved">المحفوظة · ${state.opportunities.length}</button></div><div class="notice info">المطابقة الحالية تعتمد على تصنيف القدرات والاحتياجات وقواعد محددة. خدمة الذكاء الاصطناعي السحابية تنتظر التفعيل.</div>`+(list.length?`<div class="opportunity-grid">${list.map(opportunityCard).join('')}</div>`:empty(oppTab==='saved'?'اختر الفرص التي تهمك':'أضف قدرة واحتياجا متكاملين',oppTab==='saved'?'افتح أي ترشيح ثم احفظه للمتابعة.':'كلما كانت المعلومة أكثر تحديدا، أصبحت مراجعة التكامل أسهل.',oppTab==='saved'?'discover':'add-record',oppTab==='saved'?'عرض الترشيحات':'إضافة معرفة'));}
function renderIntros(){const steps=Object.keys(STAGES).filter(x=>x!=='paused');$('#main').innerHTML=pageHead('طلبات التعارف','سجل نتيجة التواصل والموافقات، ثم تابع الخطوة التالية.')+`<div class="notice info">هذه متابعة داخل مساحتك. تحديث الحالة أو حفظ طلب تعارف لا يرسل رسائل أو دعوات للأطراف.</div>`+(state.intros.length?`<div class="intro-list">${state.intros.map(i=>{const a=person(i.fromId),b=person(i.toId);if(!a||!b)return '';const pos=steps.indexOf(i.stage);return `<article class="card"><div class="card-top"><div><h3>${esc(i.title)}</h3><p>${esc(a.name)} مع ${esc(b.name)}</p></div>${pill(STAGES[i.stage],i.stage==='completed'?'green':'copper')}</div><div class="progress" aria-hidden="true">${steps.map((x,n)=>`<i class="${n<=pos?'on':''}"></i>`).join('')}</div><div class="meta-row">${pill(i.consentA?'موافقة الطرف الأول موثقة':'موافقة الطرف الأول مطلوبة',i.consentA?'green':'gray')}${pill(i.consentB?'موافقة الطرف الثاني موثقة':'موافقة الطرف الثاني مطلوبة',i.consentB?'green':'gray')}</div><p>${esc(i.nextStep||'حدد الخطوة التالية بعد مراجعة الفرصة.')}</p><div class="card-bottom"><span>${fmt(i.due)} · ${esc(i.owner||'أنا')}</span><button class="btn secondary" data-action="edit-intro" data-id="${esc(i.id)}">تحديث المتابعة ←</button></div></article>`;}).join('')}</div>`:empty('التعارف يبدأ بفرصة','افتح ترشيحا مناسبا، وراجعه، ثم سجل طلب تعارف.','discover','راجع الفرص'));}
function renderTasks(){const list=state.tasks.filter(t=>taskTab==='all'||(taskTab==='done'?t.done:!t.done)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));$('#main').innerHTML=pageHead('المتابعة','لكل فرصة صاحب خطوة وموعد للرجوع إليها.','<button class="btn" data-action="add-task">＋ إضافة متابعة</button>')+`<div class="tab-chips">${[['open','المفتوحة'],['done','المكتملة'],['all','الكل']].map(([k,v])=>`<button class="chip ${taskTab===k?'active':''}" data-action="task-tab" data-tab="${k}">${v}</button>`).join('')}</div>`+(list.length?`<div class="table-wrap"><table class="task-table"><thead><tr><th>المتابعة</th><th>المسؤول</th><th>الموعد</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${list.map(t=>`<tr><td><strong class="${t.done?'task-done':''}">${esc(t.title)}</strong><small>${esc(t.notes||'')}</small></td><td>${esc(t.owner||'أنا')}</td><td>${fmt(t.due)}</td><td>${pill(t.done?'مكتملة':t.due&&t.due<day()?'متأخرة':'قائمة',t.done?'green':t.due&&t.due<day()?'red':'copper')}</td><td><div class="actions"><button class="check-btn" data-action="toggle-task" data-id="${esc(t.id)}" aria-label="${t.done?'إعادة فتح':'إنجاز'} ${esc(t.title)}">${t.done?'↶':'✓'}</button><button class="text-btn" data-action="edit-task" data-id="${esc(t.id)}">تعديل</button></div></td></tr>`).join('')}</tbody></table></div>`:empty('مساحة للخطوة القادمة','أضف متابعة لتأكيد معلومة أو مراجعة فرصة.','add-task','إضافة متابعة'));}
function renderSettings(){$('#main').innerHTML=pageHead('مساحة العمل','طريقة الحفظ، والنسخ الاحتياطية، وجاهزية الاتصال.')+`<div class="settings-grid"><section class="card"><span class="ey">الحفظ الحالي</span><h3>${mode==='demo'?'مساحة تجربة مؤقتة':'حفظ محلي مشفر'}</h3><p>${mode==='demo'?'جولة ببيانات افتراضية. ابدأ مساحتك الخاصة لحفظ معلوماتك.':'الحفظ في هذا المتصفح فقط، بكلمة مرور تختارها. فقدان كلمة المرور أو مسح بيانات المتصفح دون نسخة احتياطية قد يفقدك الوصول.'}</p><div class="actions"><button class="btn" data-action="workspace">${mode==='demo'?'مساحتي الخاصة':'قفل المساحة'}</button>${mode==='private'?'<button class="btn secondary" data-action="backup">نسخة احتياطية مشفرة</button>':''}</div></section><section class="card"><span class="ey">الحسابات المشتركة</span><h3>دائرة الأعضاء</h3><p>بانتظار ربط قاعدة البيانات وتفعيل حسابات الأعضاء وصلاحياتهم. أذونات المشاركة الحالية تسجل رغبتك فقط، ولا تنشر البيانات.</p>${pill('بانتظار الربط','copper')}</section><section class="card"><span class="ey">محرك الفرص</span><h3>مطابقة أولية قابلة للتفسير</h3><p>تعمل بقواعد داخل المتصفح. المعالجة بالذكاء الاصطناعي السحابي تحتاج تفعيل الخدمة ومراجعة سياسة البيانات.</p>${pill('القواعد تعمل · الذكاء السحابي ينتظر التفعيل','gray')}</section><section class="card"><span class="ey">نقل البيانات</span><h3>استيراد واستعادة</h3><p>استورد معرفة من ملف CSV بعد مراجعة المعاينة، أو افتح نسخة احتياطية مشفرة على هذا الجهاز.</p><div class="actions"><button class="btn secondary" data-action="import-csv">استيراد CSV</button><button class="btn secondary" data-action="restore">استعادة نسخة</button></div></section><section class="card span2"><span class="ey">الخصوصية والمشاركة</span><h3>الأذن يسبق التعارف</h3><p>استخدم بيانات يحق لك الاحتفاظ بها لهذا الغرض. تجنب التفاصيل الحساسة. مطابقة المعلومات تتم داخل متصفحك، ولا ترسل النسخة الحالية محتوى سجلاتك إلى خدمة ذكاء اصطناعي.</p><p>التشفير المحلي يحمي البيانات المخزنة، لكنه لا يغني عن حماية جهازك ومراجعة الأمان قبل التوسع. تحميل الخط والشعار يتم من أصول الهوية المنشورة.</p></section>${mode==='private'?'<section class="card danger-zone span2"><h3>إدارة بيانات المساحة</h3><p>حذف المساحة يزيل النسخة المشفرة من هذا المتصفح فقط. النسخ التي سبق أن حفظتها تبقى لديك.</p><button class="btn danger" data-action="erase">حذف المساحة من هذا المتصفح</button></section>':'<section class="card span2"><h3>بدء التجربة من جديد</h3><p>استعد البيانات الافتراضية الأصلية للتجربة.</p><button class="btn secondary" data-action="reset-demo">إعادة التجربة</button></section>'}</div>`;}
function renderLocked(){$('#main').innerHTML=pageHead('مساحتي الخاصة','الوصول بكلمة المرور التي اخترتها لهذه المساحة.')+empty('معرفتك محفوظة','افتح المساحة للوصول إلى السجلات والفرص والمتابعات.','workspace','فتح المساحة')+'<div class="actions mt"><button class="text-btn" data-action="restore">استعادة نسخة احتياطية</button><button class="text-btn" data-action="demo">استعراض التجربة ←</button></div>';}
function modal(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;if(!$('#dialog').open)$('#dialog').showModal();$('#dialog').scrollTop=0;setTimeout(()=>$('#dialogBody input:not([type=checkbox]),#dialogBody textarea,#dialogBody button')?.focus(),50);}
function close(){if($('#dialogBody form')?.dataset.dirty==='1'&&!confirm('إغلاق التعديلات الحالية دون حفظ؟'))return;$('#dialog').close();$('#dialogBody').innerHTML='';importDraft=[];}
function closeSaved(){$('#dialogBody form')?.removeAttribute('data-dirty');$('#dialog').close();$('#dialogBody').innerHTML='';importDraft=[];}
function field(name,label,value='',extra=''){return `<label class="field"><span>${label}</span><input name="${name}" value="${esc(value)}" ${extra}></label>`;}
function area(name,label,value='',hint=''){return `<label class="field span2"><span>${label}</span><textarea name="${name}" maxlength="${name==='notes'?4000:2000}">${esc(value)}</textarea>${hint?`<small class="hint">${hint}</small>`:''}</label>`;}
function recordForm(id){const r=person(id)||{type:'company',sourceDate:day(),reviewDate:day(30),scope:'saudi',visibility:'private',verification:'followup',connector:'أنا',canIntroduce:false};modal(id?'تعديل المعرفة':'إضافة معرفة',`<form id="recordForm" data-id="${esc(id||'')}"><div class="form-section">الشخص أو الجهة</div><div class="form-grid">${field('name','الاسم',r.name,'required maxlength="160" autocomplete="off"')}<label class="field"><span>نوع السجل</span><select name="type">${options({company:'جهة',person:'شخص'},r.type)}</select></label>${field('role','الصفة أو النشاط',r.role,'maxlength="160"')}${field('sector','القطاع',r.sector,'maxlength="100" list="sectors"')}<datalist id="sectors"><option>المقاهي</option><option>الضيافة</option><option>التقنية</option><option>الصناعة</option><option>الخدمات</option></datalist>${field('city','المدينة',r.city,'maxlength="100"')}<label class="field"><span>نطاق التعاون</span><select name="scope">${options({saudi:'المدن المختلفة مناسبة',city:'المدينة نفسها فقط'},r.scope)}</select></label></div><div class="form-section">المعرفة التي قد تصنع فرصة</div><div class="form-grid">${area('offers','ماذا يقدم؟',r.offers,'مثال: تحميص قهوة بعلامة العميل، أو تطوير منصة طلبات.')}${area('needs','عما يبحث؟',r.needs,'اكتب الاحتياج القائم، بدلا من وصف عام للنشاط.')}${area('constraints','شروط أو حدود التعاون',r.constraints)}</div><div class="form-section">صاحب العلاقة ومصدر المعلومة</div><div class="form-grid">${field('connector','من يعرفه؟',r.connector,'maxlength="120"')}${field('source','كيف عرفت المعلومة؟',r.source,'maxlength="300" placeholder="لقاء مباشر، أو تصريح من صاحبها"')}${field('sourceDate','تاريخ المعلومة',r.sourceDate,'type="date"')}${field('reviewDate','موعد مراجعتها',r.reviewDate,'type="date"')}<label class="field"><span>درجة التحقق</span><select name="verification">${options(VERIFICATION,r.verification)}</select></label><label class="field"><span>إذن المشاركة المقترح</span><select name="visibility">${options(VISIBILITY,r.visibility)}</select></label>${area('notes','ملاحظة خاصة',r.notes)}</div><label class="checkbox-row"><input type="checkbox" name="canIntroduce" ${r.canIntroduce?'checked':''}><span>صاحب العلاقة يستطيع تقديم تعارف فعلي.</span></label><div class="notice info">كل البيانات تبقى في مساحتك الحالية. إذن المشاركة يسجل رغبتك للمتابعة فقط؛ المشاركة بين الأعضاء تنتظر الربط.</div>${mode==='demo'?'<div class="notice">هذه مساحة تجربة. استخدم بيانات افتراضية، أو افتح مساحتك الخاصة للمعلومات التي تخصك.</div>':''}<p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="btn secondary" data-action="close">إلغاء</button><button type="submit" class="btn">حفظ المعرفة</button></div></form>`);}
function viewRecord(id){const r=person(id);if(!r)return;modal(r.name,`<div class="actions">${pill(r.role||r.type)}${pill(VERIFICATION[r.verification],r.verification==='confirmed'?'green':'copper')}${pill(VISIBILITY[r.visibility],'gray')}</div><div class="detail-grid">${[['يقدم',r.offers],['يبحث عن',r.needs],['صاحب العلاقة',r.connector],['المصدر',r.source],['تاريخ المعلومة',fmt(r.sourceDate)],['موعد المراجعة',fmt(r.reviewDate)],['نطاق التعاون',r.scope==='city'?`داخل ${r.city}`:'المدن المختلفة مناسبة'],['طريق التعارف',r.canIntroduce?'يستطيع تقديم التعارف':'يحتاج تأكيد']].map(([k,v])=>`<div class="detail-block"><small>${esc(k)}</small><p>${esc(v||'تضاف لاحقا')}</p></div>`).join('')}</div>${r.constraints?`<h3>شروط التعاون</h3><p class="detail-copy">${esc(r.constraints)}</p>`:''}${r.notes?`<div class="notice info"><strong>ملاحظة خاصة</strong><p class="detail-copy">${esc(r.notes)}</p></div>`:''}<div class="form-actions"><button class="btn danger" data-action="delete-record" data-id="${esc(id)}">حذف السجل</button><button class="btn" data-action="edit-record" data-id="${esc(id)}">تعديل المعرفة</button></div>`);}
function viewMatch(id){const m=savedMatch(id);if(!m)return;const a=person(m.fromId),b=person(m.toId);if(!a||!b)return;const saved=state.opportunities.some(x=>x.id===id),intro=state.intros.find(x=>x.matchId===id);modal(m.title,`<div class="notice info">ترشيح أولي للمراجعة، مبني على المعلومات المسجلة. درجة التشابه ليست احتمالا لنجاح الصفقة.</div><div class="detail-grid"><div class="detail-block"><small>${esc(a.name)} يبحث عن</small><p>${esc(a.needs)}</p><small>المصدر: ${esc(a.source)} · ${fmt(a.sourceDate)}</small></div><div class="detail-block"><small>${esc(b.name)} يقدم</small><p>${esc(b.offers)}</p><small>المصدر: ${esc(b.source)} · ${fmt(b.sourceDate)}</small></div></div><h3>سبب الترشيح</h3><p class="detail-copy">${esc((m.reasons||[]).join('\n'))}</p><h3 class="mt">ما نحتاج التأكد منه</h3><p class="detail-copy">${esc((m.checks||[]).map(x=>'• '+x).join('\n'))}</p><h3 class="mt">طريق التعارف المقترح</h3><div class="route"><div><b>${esc(a.name)}</b><small>الطرف الأول</small></div><span>←</span><div><b>${esc(a.connector||'يحدد لاحقا')}</b><small>صاحب العلاقة</small></div><span>←</span><div><b>${esc(b.connector||'يحدد لاحقا')}</b><small>صاحب العلاقة</small></div><span>←</span><div><b>${esc(b.name)}</b><small>الطرف الثاني</small></div></div><div class="notice">حفظ الطلب ينشئ متابعة لديك فقط. اجمع الإذن المناسب قبل كشف الأسماء أو تفاصيل المعلومة.</div><div class="form-actions">${saved?`<button class="btn secondary" data-action="remove-match" data-id="${esc(id)}">إزالة من المحفوظة</button>`:`<button class="btn secondary" data-action="save-match" data-id="${esc(id)}">حفظ الفرصة</button>`}<button class="btn" data-action="${intro?'edit-intro':'create-intro'}" data-id="${esc(intro?.id||id)}">${intro?'فتح متابعة التعارف':'تسجيل طلب تعارف'}</button></div>`);}
function introForm(id){const i=state.intros.find(x=>x.id===id);if(!i)return;const a=person(i.fromId),b=person(i.toId);modal('متابعة التعارف',`<form id="introForm" data-id="${esc(id)}"><p class="detail-copy">${esc(a?.name)} مع ${esc(b?.name)}</p><div class="notice info">وثق الموافقات التي حصلت عليها بنفسك. هذا النموذج لا يرسل طلب موافقة للأطراف.</div><div class="stack"><label class="consent"><input type="checkbox" name="consentA" ${i.consentA?'checked':''}><span>موافقة ${esc(a?.name)}<small>وافق على التعارف وعلى مشاركة المعلومات اللازمة له.</small></span></label><label class="consent"><input type="checkbox" name="consentB" ${i.consentB?'checked':''}><span>موافقة ${esc(b?.name)}<small>وافق على التعارف وعلى مشاركة المعلومات اللازمة له.</small></span></label>${field('consentEvidence','مرجع الموافقة وتاريخها',i.consentEvidence,'maxlength="500" placeholder="مثال: اتصال بالطرفين بتاريخ…"')}</div><div class="form-section">الخطوة التالية</div><div class="form-grid"><label class="field"><span>مرحلة التعارف</span><select name="stage">${options(STAGES,i.stage)}</select></label>${field('owner','مسؤول المتابعة',i.owner||'أنا','maxlength="120"')}${field('due','موعد المتابعة',i.due,'type="date"')}${field('nextStep','ما الخطوة القادمة؟',i.nextStep,'maxlength="500"')}${area('outcome','النتيجة أو الملاحظة',i.outcome)}</div><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="btn secondary" data-action="close">إلغاء</button><button type="submit" class="btn">حفظ المتابعة</button></div></form>`);}
function taskForm(id){const t=state.tasks.find(x=>x.id===id)||{owner:'أنا',due:day(1)};modal(id?'تعديل المتابعة':'إضافة متابعة',`<form id="taskForm" data-id="${esc(id||'')}"><div class="form-grid"><div class="span2">${field('title','ما المطلوب؟',t.title,'required maxlength="250"')}</div>${field('owner','المسؤول',t.owner,'maxlength="120"')}${field('due','الموعد',t.due,'type="date"')}${area('notes','تفاصيل المتابعة',t.notes)}</div><p class="form-error" role="alert"></p><div class="form-actions">${id?`<button type="button" class="btn danger" data-action="delete-task" data-id="${esc(id)}">حذف</button>`:'<button type="button" class="btn secondary" data-action="close">إلغاء</button>'}<button type="submit" class="btn">حفظ المتابعة</button></div></form>`);}
function workspace(){if(mode==='private'){lockWorkspace();return;}const existing=vault.exists();modal(existing?'افتح مساحتك الخاصة':'ابدأ مساحتك الخاصة',`<form id="vaultForm"><p class="detail-copy">${existing?'أدخل كلمة المرور التي اخترتها لهذا المتصفح.':'تبدأ بمساحة فارغة. تختار كلمة مرور، وتحفظ المعرفة والفرص مشفرة في هذا المتصفح فقط.'}</p><div class="notice">كلمة المرور لا ترسل إلى خادم. فقدانها قد يفقدك الوصول؛ احتفظ بها وبنسخة احتياطية في مكان آمن.</div><div class="stack">${field('password','كلمة المرور','','type="password" required minlength="12" maxlength="200" autocomplete="'+(existing?'current-password':'new-password')+'"')}${existing?'':field('confirm','تأكيد كلمة المرور','','type="password" required minlength="12" maxlength="200" autocomplete="new-password"')}</div>${existing?'':'<label class="checkbox-row"><input type="checkbox" name="understood" required><span>أفهم أن البيانات تحفظ في هذا المتصفح فقط، وأن النسخة الاحتياطية ضرورية لاستعادتها على جهاز آخر.</span></label>'}<p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="btn secondary" data-action="restore">استعادة نسخة</button><button class="btn" type="submit">${existing?'فتح المساحة':'إنشاء المساحة'}</button></div></form>`);}
async function lockWorkspace(){await mutationQueue.catch(()=>{});await vault.lock();mode='locked';state=emptyState();q='';closeSaved();render();toast('تم قفل المساحة.');}
function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function restoreForm(){modal('استعادة نسخة احتياطية',`<form id="restoreForm"><p class="detail-copy">اختر ملف النسخة المشفرة، وأدخل كلمة مرورها.</p>${vault.exists()?'<div class="notice">الاستعادة تستبدل المساحة المحفوظة في هذا المتصفح بعد التحقق من الملف وكلمة المرور. احفظ نسختك الحالية أولا.</div>':''}<div class="stack"><label class="field"><span>ملف النسخة</span><input name="backup" type="file" accept=".json,.kbvault" required></label>${field('password','كلمة مرور النسخة','','type="password" required autocomplete="current-password"')}</div><label class="checkbox-row"><input name="understood" type="checkbox" required><span>أوافق على استعادة هذه النسخة إلى هذا المتصفح.</span></label><p class="form-error" role="alert"></p><div class="form-actions"><button class="btn secondary" type="button" data-action="close">إلغاء</button><button class="btn" type="submit">فتح النسخة</button></div></form>`);}
function importCSV(){modal('استيراد المعرفة',`<div class="notice info">ابدأ بالقالب، ثم راجع المعاينة قبل الحفظ. الحد 300 سجل في المرة. تدخل السجلات بأذونات خاصة وبحالة «تحتاج تأكيد».</div>${mode==='demo'?'<div class="notice">في التجربة استخدم ملفات افتراضية فقط. افتح مساحتك الخاصة للبيانات التي تخصك.</div>':''}<div class="actions"><button class="btn secondary" data-action="csv-template">قالب CSV ↓</button></div><label class="field mt"><span>ملف CSV بترميز UTF-8</span><input id="csvFile" type="file" accept=".csv,text/csv"></label><div id="csvPreview" class="mt"></div>`);}
function help(){modal('من المعرفة إلى الخطوة القادمة',`<div class="step-list">${[['01','أضف معرفة','سجل شخصا أو جهة، وقدرة أو احتياجا، وصاحب العلاقة ومصدر المعلومة.'],['02','راجع فرصة التكامل','افتح الترشيح واقرأ سبب الملاءمة، وما يجب التأكد منه قبل التعارف.'],['03','وثق الموافقة','احصل على موافقة الأطراف خارج المنصة، ثم سجلها في طلب التعارف.'],['04','تابع النتيجة','حدد المسؤول والموعد والخطوة التالية، وحدث ما نتج عن اللقاء.']].map(([n,t,d])=>`<div class="step"><b>${n}</b><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}</div><div class="notice info">النسخة الأولى تعمل بالتجربة والحفظ المحلي المشفر. الحسابات المشتركة والمعالجة بالذكاء الاصطناعي السحابي تنتظر التفعيل.</div>`);}
const actions={
'add-record':()=>recordForm(), 'edit-record':id=>recordForm(id), 'view-record':viewRecord, 'view-match':viewMatch,
'add-task':()=>taskForm(), 'edit-task':taskForm,'edit-intro':introForm,
'close':close,'workspace':workspace,'settings':()=>go('settings'),'knowledge':()=>go('knowledge'),'help':help,
'discover':()=>{oppTab='suggested';go('opportunities');},'refresh-matches':()=>{renderOpportunities();toast('تم تحديث الترشيحات من المعرفة المسجلة.');},
'opp-tab':(_id,el)=>{oppTab=el.dataset.tab;renderOpportunities();},'task-tab':(_id,el)=>{taskTab=el.dataset.tab;renderTasks();},
'menu':(_id,el)=>{const opened=$('#sidebar').classList.toggle('open');el.setAttribute('aria-expanded',String(opened));},
'demo':async()=>{if(mode==='private')await lockWorkspace();mode='demo';state=demoState();go('home');},
'reset-demo':()=>{if(mode==='demo'&&confirm('استعادة بيانات التجربة الأصلية؟')){state=demoState();render();toast('بدأت التجربة من جديد.');}},
'save-match':async id=>{const match=savedMatch(id);if(!match)throw Error('الترشيح غير موجود.');await change(s=>{if(!s.opportunities.some(x=>x.id===id))s.opportunities.push({...match,savedAt:new Date().toISOString()});},'تم حفظ الفرصة');viewMatch(id);},
'remove-match':async id=>{await change(s=>{s.opportunities=s.opportunities.filter(x=>x.id!==id);},'تمت إزالة الفرصة من المحفوظة');closeSaved();},
'create-intro':async id=>{const match=savedMatch(id);if(!match)return;const found=state.intros.find(x=>x.matchId===id);if(found){introForm(found.id);return;}const iid=uid();await change(s=>{if(!s.opportunities.some(x=>x.id===id))s.opportunities.push({...match,savedAt:new Date().toISOString()});s.intros.push({id:iid,matchId:id,title:match.title,fromId:match.fromId,toId:match.toId,stage:'review',owner:'أنا',due:day(2),nextStep:'مراجعة الإذن مع صاحبي العلاقتين.',consentA:false,consentB:false,consentEvidence:'',outcome:'',createdAt:new Date().toISOString()});},'تم تسجيل متابعة تعارف');introForm(iid);},
'delete-record':async id=>{if(!confirm('حذف السجل والفرص وطلبات التعارف المرتبطة به من هذه المساحة؟'))return;await change(s=>{s.records=s.records.filter(r=>r.id!==id);s.opportunities=s.opportunities.filter(x=>x.fromId!==id&&x.toId!==id);s.intros=s.intros.filter(x=>x.fromId!==id&&x.toId!==id);},'تم حذف السجل وارتباطاته');closeSaved();},
'delete-task':async id=>{if(!confirm('حذف هذه المتابعة؟'))return;await change(s=>{s.tasks=s.tasks.filter(x=>x.id!==id);},'تم حذف المتابعة');closeSaved();},
'check-updates':()=>{go('knowledge');},
'backup':async()=>{if(mode!=='private')throw Error('افتح المساحة الخاصة أولا.');await mutationQueue.catch(()=>{});download(`knowledge-bank-${day()}.kbvault`,await vault.backup(),'application/json');toast('تم تجهيز نسخة مشفرة. احتفظ بكلمة مرورها.');},
'restore':restoreForm,'import-csv':importCSV,
'csv-template':()=>download('knowledge-bank-template.csv','\uFEFFالاسم,الصفة,المدينة,القطاع,صاحب_العلاقة,يقدم,يبحث_عن,المصدر\r\nجهة افتراضية,محمصة,جدة,القهوة,صاحب العلاقة,تحميص قهوة بعلامة العميل,عملاء ضيافة,مثال للتجربة\r\n','text/csv;charset=utf-8'),
'commit-csv':async()=>{if(!importDraft.length)return;const records=importDraft;await change(s=>{const existing=new Set(s.records.map(r=>r.name.trim()+'|'+r.city.trim()));for(const r of records){const key=r.name.trim()+'|'+r.city.trim();if(!existing.has(key)){s.records.push(r);existing.add(key);}}},'تم استيراد السجلات الجديدة');closeSaved();go('knowledge');},
'erase':()=>modal('حذف المساحة من هذا المتصفح',`<form id="eraseForm"><div class="notice">احفظ نسخة احتياطية أولا. ستبقى الملفات التي سبق أن نزلتها خارج المتصفح كما هي.</div>${field('confirm','اكتب: حذف المساحة','','required autocomplete="off"')}<p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="btn secondary" data-action="close">إلغاء</button><button type="submit" class="btn danger">حذف المساحة</button></div></form>`),
};
actions['toggle-task']=async id=>change(s=>{const t=s.tasks.find(x=>x.id===id);if(t)t.done=!t.done;},'تم تحديث المتابعة');
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=actions[el.dataset.action];if(!action)return;try{await action(el.dataset.id,el);}catch(e){toast(e.message||'تعذر تنفيذ الإجراء. حاول مرة أخرى.');}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(Object.hasOwn(labels,next)){page=next;render();$('#sidebar').classList.remove('open');$('[data-action="menu"]').setAttribute('aria-expanded','false');}});
document.addEventListener('input',event=>{lastActivity=Date.now();const form=event.target.closest('#recordForm,#introForm,#taskForm');if(form)form.dataset.dirty='1';if(event.target.id==='knowledgeSearch'){q=event.target.value;renderKnowledgeResults();}});
document.addEventListener('change',async event=>{try{if(event.target.id==='sectorFilter'){sectorFilter=event.target.value;renderKnowledgeResults();}if(event.target.id==='visibilityFilter'){visibilityFilter=event.target.value;renderKnowledgeResults();}if(event.target.id==='csvFile'){const file=event.target.files[0];if(!file)return;if(file.size>2_000_000)throw Error('الحد لحجم الملف 2 MB.');importDraft=recordsFromCSV(await file.text());const existing=new Set(state.records.map(r=>r.name.trim()+'|'+r.city.trim()));let duplicates=0;for(const r of importDraft){const k=r.name.trim()+'|'+r.city.trim();if(existing.has(k))duplicates++;else existing.add(k);}$('#csvPreview').innerHTML=`<p class="results-info">${importDraft.length} سجل في الملف · ${duplicates} تطابق اسم ومدينة سيجري تجاوزه دون دمج تلقائي.</p><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>يقدم</th><th>يبحث عن</th></tr></thead><tbody>${importDraft.slice(0,8).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.offers)}</td><td>${esc(r.needs)}</td></tr>`).join('')}</tbody></table></div><p class="hint">معاينة أول 8 سجلات. المصدر والدرجة والأذونات قابلة للتعديل بعد الحفظ.</p><div class="form-actions"><button class="btn" data-action="commit-csv">اعتماد الاستيراد</button></div>`;}}catch(e){importDraft=[];if($('#csvPreview'))$('#csvPreview').textContent=e.message;toast(e.message);}});
document.addEventListener('submit',async event=>{const form=event.target;if(!['recordForm','introForm','taskForm','vaultForm','restoreForm','eraseForm'].includes(form.id))return;event.preventDefault();const err=form.querySelector('.form-error'),submit=form.querySelector('[type=submit]');err.textContent='';submit.disabled=true;const data=Object.fromEntries(new FormData(form)),id=form.dataset.id;try{
if(form.id==='recordForm'){const record=validateRecord({...data,id:id||uid(),canIntroduce:form.elements.canIntroduce.checked,createdAt:person(id)?.createdAt||new Date().toISOString()});await change(s=>{const i=s.records.findIndex(x=>x.id===record.id);if(i<0)s.records.push(record);else s.records[i]=record;},'تم حفظ المعرفة');closeSaved();}
if(form.id==='taskForm'){await change(s=>{const current=s.tasks.find(x=>x.id===id);const task={id:id||uid(),title:String(data.title).trim(),owner:data.owner||'أنا',due:data.due,notes:data.notes||'',done:current?.done||false};if(!task.title)throw Error('اكتب عنوان المتابعة.');const i=s.tasks.findIndex(x=>x.id===task.id);if(i<0)s.tasks.push(task);else s.tasks[i]=task;},'تم حفظ المتابعة');closeSaved();}
if(form.id==='introForm'){const update={...data,consentA:form.elements.consentA.checked,consentB:form.elements.consentB.checked};if(!canAdvance(update,update.stage))throw Error('وثق موافقة الطرفين ومرجعها قبل الانتقال إلى التعارف أو المراحل التالية.');if((update.consentA||update.consentB)&&!update.consentEvidence.trim())throw Error('أضف مرجع الموافقة وتاريخها.');if(update.stage==='completed'&&!update.outcome.trim())throw Error('اكتب النتيجة قبل إكمال التعارف.');await change(s=>{const i=s.intros.findIndex(x=>x.id===id);if(i<0)throw Error('متابعة التعارف غير موجودة.');s.intros[i]={...s.intros[i],...update,updatedAt:new Date().toISOString()};},'تم تحديث متابعة التعارف');closeSaved();}
if(form.id==='vaultForm'){if(!vault.supported())throw Error('التشفير يحتاج متصفحا حديثا واتصال HTTPS.');if(vault.exists())state=await vault.unlock(data.password);else{if(data.password!==data.confirm)throw Error('كلمتا المرور غير متطابقتين.');const fresh=emptyState();await vault.create(data.password,fresh);state=fresh;}mode='private';q='';lastActivity=Date.now();closeSaved();go('home');toast('مساحتك مفتوحة. الحفظ في هذا المتصفح فقط.');}
if(form.id==='restoreForm'){const file=form.elements.backup.files[0];if(!file||file.size>8_000_000)throw Error('اختر نسخة احتياطية بحجم أقل من 8 MB.');if(vault.exists()&&!confirm('استبدال المساحة الحالية بالنسخة المختارة بعد التحقق منها؟')){submit.disabled=false;return;}state=await vault.restore(await file.text(),data.password);mode='private';lastActivity=Date.now();closeSaved();go('home');toast('تمت استعادة المساحة.');}
if(form.id==='eraseForm'){if(data.confirm.trim()!=='حذف المساحة')throw Error('اكتب العبارة كما هي لتأكيد الحذف.');await mutationQueue.catch(()=>{});await vault.erase();state=demoState();mode='demo';closeSaved();go('home');toast('حذفت المساحة من هذا المتصفح.');}
}catch(e){err.textContent=e.message||'تعذر الحفظ. لم يعتمد التغيير.';submit.disabled=false;}});
$('#dialog').addEventListener('cancel',event=>{event.preventDefault();close();});
for(const type of ['pointerdown','keydown'])document.addEventListener(type,()=>{lastActivity=Date.now();},{passive:true});
setInterval(()=>{if(mode==='private'&&Date.now()-lastActivity>15*60*1000)lockWorkspace().catch(()=>toast('تعذر إتمام القفل. احفظ نسخة احتياطية.'));},30000);
window.addEventListener('beforeunload',e=>{if(pending){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',event=>{if(event.key===vault.storageKey&&mode==='private')lockWorkspace().then(()=>toast('تغيرت المساحة في نافذة أخرى. افتحها من جديد.')).catch(()=>{});});
render();
