/** Domain logic. No network requests and no generated claims. */
export const VERSION=1;
export const VISIBILITY={private:'خاص بي',intro:'التعارف عن طريقي',circle:'مقترح للدائرة'};
export const VERIFICATION={confirmed:'معلومة مؤكدة',followup:'تحتاج تأكيد',heard:'معلومة أولية'};
export const STAGES={review:'قيد المراجعة',consent:'بانتظار الموافقة',introduced:'تم التعارف',meeting:'تم اللقاء',followup:'متابعة',completed:'نتيجة موثقة',paused:'مؤجلة'};
export const CATEGORIES={coffee:'القهوة والتحميص',operation:'التشغيل',packaging:'التعبئة والتغليف',technology:'التقنية',logistics:'النقل والتوزيع',consulting:'الخبرة والاستشارات',space:'المواقع والمساحات',marketing:'التسويق'};
const TERMS={coffee:['قهوة','قهوه','تحميص','محمصة','محامص','بن','coffee'],operation:['تشغيل','مشغل','ادارة مطعم','اداره مقهى','operator'],packaging:['تغليف','تعبئة','تعبئه','عبوات','اكياس','اكواب','packaging'],technology:['تقنية','تقنيه','برمجة','برمجه','مبرمج','نظام','منصة','منصه','تطبيق','تقني','software','developer','روبوت'],logistics:['نقل','توزيع','موزع','شحن','مستودع','لوجستي','logistics'],consulting:['استشارة','استشاره','استشارات','مستشار','خبرة','حوكمة','خبير'],space:['مساحة','مساحه','موقع','مواقع','تأجير','تاجير','عقار'],marketing:['تسويق','حملات','اعلان','ترويج','marketing']};
export function normalize(text){return String(text??'').toLowerCase().normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();}
export function classify(text){const n=normalize(text);return Object.entries(TERMS).filter(([,words])=>words.some(w=>{const x=normalize(w);return x.length>2?n.includes(x):n.split(' ').includes(x);})).map(([key])=>key);}
export const uid=()=>crypto.randomUUID();
export function day(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function emptyState(){return {version:VERSION,records:[],opportunities:[],intros:[],tasks:[],activity:[]};}
export function demoState(){const s=emptyState();const base={type:'company',role:'',source:'لقاء تعارف افتراضي',sourceDate:day(-7),reviewDate:day(30),verification:'confirmed',visibility:'intro',constraints:'التفاصيل التجارية تحتاج نقاشا مستقلا.',notes:'',canIntroduce:true,scope:'saudi',createdAt:new Date().toISOString()};
const rows=[
['r1','محمصة المدار','شركة تحميص','جدة','فهد','تحميص قهوة وتوريد بعلامة العميل. طاقة متاحة للطلبات المنتظمة.','عملاء ضيافة بعقود توريد منتظمة.','القهوة'],
['r2','ضيافة المدى','تشغيل ضيافة','جدة','سامي','إدارة ضيافة مؤسسية وعقود شراء دورية.','محمصة لتوريد القهوة بعلامتنا الخاصة.','الضيافة'],
['r3','حلول العبوة','مصنع تغليف','الرياض','عبدالله','تصنيع عبوات وأكياس تغليف بكميات مرنة للمقاهي.','جهات تطلب عبوات مخصصة دوريا.','الصناعة'],
['r4','مقهى نقطة','مقهى متخصص','جدة','فهد','منتجات قهوة مختصة وطلبات متكررة.','مورد تغليف للأكواب والأكياس بهوية المقهى.','المقاهي'],
['r5','سلمان الراشد','مطور منتجات','الرياض','سامي','تطوير منصات وبرمجة تطبيقات للشركات.','شريك تسويق لتجربة دخول قطاع الضيافة.','التقنية'],
['r6','مطاعم مواسم','مجموعة مطاعم','الرياض','عبدالله','تشغيل مطاعم وجاهزية لاختبار حلول رقمية.','مبرمج لتطوير منصة طلبات ومتابعة الموردين.','المطاعم'],
['r7','ليان الحربي','خبيرة تشغيل','جدة','فهد','استشارات تشغيل المقاهي وتطوير الإجراءات وتدريب الفريق.','مشاريع مقاه تحتاج استشارات تشغيل.','الاستشارات'],
['r8','ضيافة أفق','مشروع ضيافة','المدينة المنورة','سامي','مشروع مقهى قيد التجهيز داخل منشأة ضيافة.','خبيرة تشغيل لوضع الإجراءات وتدريب فريق المقهى.','الضيافة']
];s.records=rows.map(([id,name,role,city,connector,offers,needs,sector])=>({...base,id,name,role,city,connector,offers,needs,sector,type:['r5','r7'].includes(id)?'person':'company',verification:id==='r7'?'followup':'confirmed',reviewDate:id==='r8'?day(-1):day(30)}));
s.tasks=[{id:'t1',title:'تأكيد مواصفات توريد القهوة',owner:'أنا',due:day(1),notes:'مثال: الكمية، نوع التحميص، والعلامة الخاصة.',done:false},{id:'t2',title:'تحديث احتياج ضيافة أفق',owner:'أنا',due:day(2),notes:'مثال: التحقق من موعد التشغيل ونطاق الاستشارة.',done:false}];return s;}
export function validateRecord(input){if(!input||typeof input!=='object')throw Error('السجل غير صالح.');const out={};for(const key of ['id','name','type','role','sector','city','connector','offers','needs','constraints','source','sourceDate','reviewDate','verification','visibility','notes','scope','createdAt'])out[key]=String(input[key]??'').slice(0,key==='notes'?4000:key==='offers'||key==='needs'?2000:500);
if(!out.name.trim())throw Error('أضف اسم الشخص أو الجهة.');if(!out.offers.trim()&&!out.needs.trim())throw Error('أضف قدرة أو احتياجا واحدا على الأقل.');if(!out.id)out.id=uid();if(!['person','company'].includes(out.type))out.type='company';if(!['saudi','city'].includes(out.scope))out.scope='saudi';if(!VISIBILITY[out.visibility])out.visibility='private';if(!VERIFICATION[out.verification])out.verification='followup';for(const k of ['sourceDate','reviewDate'])if(out[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(out[k]))throw Error('صيغة التاريخ غير صحيحة.');out.canIntroduce=input.canIntroduce===true;return out;}
export function validateState(input){if(!input||input.version!==VERSION)throw Error('صيغة النسخة الاحتياطية غير متوافقة.');const state=emptyState();for(const k of ['records','opportunities','intros','tasks','activity']){if(!Array.isArray(input[k])||input[k].length>3000)throw Error('حجم البيانات أو تنسيقها غير صالح.');state[k]=structuredClone(input[k]);}state.records=state.records.map(validateRecord);const ids=new Set();for(const r of state.records){if(ids.has(r.id))throw Error('يوجد سجل مكرر في الملف.');ids.add(r.id);}for(const k of ['opportunities','intros','tasks']){const seen=new Set();for(const item of state[k]){if(!item||typeof item!=='object'||typeof item.id!=='string'||seen.has(item.id))throw Error('عنصر غير صالح في الملف.');seen.add(item.id);if(k!=='tasks'&&(!ids.has(item.fromId)||!ids.has(item.toId)))throw Error('فرصة مرتبطة بسجل غير موجود.');if(k==='intros'&&!STAGES[item.stage])throw Error('مرحلة تعارف غير صالحة.');if(k==='tasks'&&typeof item.title!=='string')throw Error('عنوان المهمة غير صالح.');}}return state;}
export function recordMatches(record,query){const q=normalize(query);if(!q)return true;const text=normalize([record.name,record.role,record.sector,record.city,record.connector,record.offers,record.needs,record.source,record.notes].join(' '));const terms=q.split(' ').filter(x=>x.length>1&&!['ابحث','احتاج','عن','في','عندي','لدي','ابي','ابغى','اريد','من','الى','جهة','جهه','شخص'].includes(x));if(!terms.length)return text.includes(q);const cats=classify(q),recordCats=classify(record.offers+' '+record.needs);return terms.every(t=>text.includes(t))||cats.some(c=>recordCats.includes(c));}
/** A directional need -> capability match. Ranking is not a probability. */
export function findMatches(records){
 const prepared=records.map(r=>({r,needs:classify(r.needs),offers:classify(r.offers),offerText:normalize(r.offers+' '+r.role),needText:normalize(r.needs),city:normalize(r.city)}));
 const buckets=new Map();for(const p of prepared)for(const c of p.offers){if(!buckets.has(c))buckets.set(c,[]);buckets.get(c).push(p);}
 let result=[],floor=-Infinity;
 for(const n of prepared){if(!n.r.needs.trim())continue;const candidates=new Set(n.needs.flatMap(c=>buckets.get(c)||[]));
 for(const p of candidates){const needer=n.r,provider=p.r;if(needer.id===provider.id||!provider.offers.trim())continue;
 if((needer.scope==='city'||provider.scope==='city')&&n.city!==p.city)continue;
 if(/محمصه|تحميص/.test(n.needText)&&!/محمصه|تحميص/.test(p.offerText))continue;
 const shared=n.needs.filter(t=>p.offers.includes(t));if(!shared.length)continue;
 const sameCity=needer.city&&n.city===p.city,stale=[needer,provider].some(x=>x.reviewDate&&x.reviewDate<day()),needsConfirm=[needer,provider].some(x=>x.verification!=='confirmed'),reachable=needer.canIntroduce&&provider.canIntroduce;
 const score=shared.length*10+(sameCity?3:0)+(reachable?2:0)-(stale?4:0)-(needsConfirm?3:0);if(result.length>=200&&score<=floor)continue;
 const reasons=[`احتياج في ${shared.map(t=>CATEGORIES[t]).join(' و')} يقابله عرض مسجل.`,sameCity?'الطرفان في المدينة نفسها.':'يلزم التأكد من ملاءمة نطاق الخدمة.'];
 const checks=['تأكيد نطاق العمل والكميات والتكلفة.','موافقة الأطراف على التعارف.'];if(stale)checks.unshift('تحديث المعلومات التي تجاوزت موعد المراجعة.');if(needsConfirm)checks.unshift('تأكيد المعلومات الأولية من أصحابها.');if(!reachable)checks.unshift('تأكيد قدرة صاحب العلاقة على تقديم التعارف.');if(needer.visibility==='private'||provider.visibility==='private')checks.unshift('مراجعة الإذن قبل مشاركة أي معلومة خاصة.');
 result.push({id:`${needer.id}~${provider.id}`,fromId:needer.id,toId:provider.id,title:`فرصة تعاون في ${CATEGORIES[shared[0]]}`,reasons,checks,score,stale,needsConfirm,category:shared[0]});
 if(result.length>=400){result.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));result=result.slice(0,200);floor=result[199].score;}
 }}return result.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,200);
}
export function canAdvance(intro,stage){if(!STAGES[stage])return false;return ['review','consent','paused'].includes(stage)||!!(intro.consentA&&intro.consentB&&intro.consentEvidence?.trim());}
export function csvParse(text){if(text.length>2_000_000)throw Error('الملف أكبر من الحد المتاح.');const rows=[];let row=[],field='',quoted=false;const src=text.replace(/^\uFEFF/,'');for(let i=0;i<src.length;i++){const ch=src[i];if(ch==='"'){if(quoted&&src[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(field);field='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&src[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field='';}else field+=ch;}if(quoted)throw Error('علامات الاقتباس في CSV تحتاج تصحيحا.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows;}
export function recordsFromCSV(text){const rows=csvParse(text);if(rows.length<2)throw Error('أضف صف بيانات بعد العناوين.');if(rows.length>301)throw Error('الحد لكل استيراد 300 سجل.');const aliases={الاسم:'name',name:'name',الصفة:'role',role:'role',المدينة:'city',city:'city',القطاع:'sector',sector:'sector',صاحب_العلاقة:'connector',connector:'connector',يقدم:'offers',offers:'offers',يبحث_عن:'needs',needs:'needs',المصدر:'source',source:'source'};const keys=rows[0].map(h=>aliases[h.trim()]);if(!keys.includes('name')||(!keys.includes('offers')&&!keys.includes('needs')))throw Error('العناوين المطلوبة: الاسم، ويقدم أو يبحث_عن.');return rows.slice(1).map((row,index)=>{const raw={id:uid(),type:'company',visibility:'private',verification:'followup',scope:'saudi',sourceDate:day(),reviewDate:day(30),canIntroduce:false};keys.forEach((k,i)=>{if(k)raw[k]=row[i]??'';});try{return validateRecord(raw);}catch(e){throw Error(`الصف ${index+2}: ${e.message}`);}});}
