import * as pdfjsLib from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.worker.min.mjs';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={file:null,originalBytes:null,pdfjsDoc:null,pages:[],activePage:1,overlays:[],history:[],signature:null,uploadSignature:null,signaturePad:null,pendingAddSignature:false,outputBlob:null,outputFile:null};
const SIG_KEY='waqqe_signature_v1';
function svgSafeText(t){return String(t).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function loading(on,text='جاري تجهيز الملف…'){$('#loadingText').textContent=text;$('#loading').classList.toggle('hidden',!on)}
function setStep(n){$$('.step').forEach(el=>{const s=+el.dataset.step;el.classList.toggle('active',s===n);el.classList.toggle('done',s<n)})}
function formatBytes(bytes){if(bytes<1024)return bytes+' B';if(bytes<1048576)return(bytes/1024).toFixed(1)+' KB';return(bytes/1048576).toFixed(1)+' MB'}
function outputName(){const name=(state.file?.name||'document.pdf').replace(/\.pdf$/i,'');return `${name}-signed.pdf`}
function currentSignature(){return state.signature}
function loadSavedSignature(){try{state.signature=localStorage.getItem(SIG_KEY)||null}catch(e){state.signature=null}updateSignatureUi()}
function updateSignatureUi(){const ready=!!state.signature;const el=$('#signatureState');el.classList.toggle('ready',ready);el.querySelector('span').textContent=ready?'التوقيع محفوظ وجاهز':'لم يتم حفظ توقيع بعد';$('#deleteSavedSignature')?.classList.toggle('hidden',!ready);renderSavedSignature()}
function renderSavedSignature(){const box=$('#savedSignatureBox');if(!box)return;if(state.signature){box.innerHTML=`<img class="saved-preview" src="${state.signature}" alt="التوقيع المحفوظ">`}else{box.innerHTML='<div class="signature-empty">لا يوجد توقيع محفوظ على هذا الجهاز.<br>ارفع صورة أو ارسم توقيعك مرة واحدة.</div>'}}

$('#pickPdf').addEventListener('click',()=>$('#pdfInput').click());
$('#changeFile').addEventListener('click',()=>$('#pdfInput').click());
$('#pdfInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)openPdf(f);e.target.value='' });
const drop=$('#dropZone');
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));
['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));
drop.addEventListener('drop',e=>{const f=[...e.dataTransfer.files].find(x=>x.type==='application/pdf'||/\.pdf$/i.test(x.name));if(f)openPdf(f);else toast('اختر ملف PDF')});

async function openPdf(file){loading(true,'جاري فتح ملف PDF…');try{const bytes=new Uint8Array(await file.arrayBuffer());const doc=await pdfjsLib.getDocument({data:bytes.slice()}).promise;state.file=file;state.originalBytes=bytes;state.pdfjsDoc=doc;state.pages=[];state.activePage=1;state.overlays=[];state.history=[];state.outputBlob=null;state.outputFile=null;$('#fileName').textContent=file.name;$('#fileInfo').textContent=`${formatBytes(file.size)} · ${doc.numPages} صفحة`;$('#uploadPanel').classList.add('hidden');$('#resultPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#hero').scrollIntoView({behavior:'smooth',block:'start'});setStep(2);await renderPdf();updateUndo();updateActivePageLabel()}catch(err){console.error(err);toast('تعذر فتح الملف. قد يكون محميًا أو تالفًا.')}finally{loading(false)}}
async function renderPdf(){const stage=$('#pdfStage');stage.innerHTML='';const maxWidth=Math.min(900,Math.max(280,stage.clientWidth-28));for(let n=1;n<=state.pdfjsDoc.numPages;n++){const page=await state.pdfjsDoc.getPage(n);const unit=page.getViewport({scale:1});const scale=maxWidth/unit.width;const viewport=page.getViewport({scale});const wrap=document.createElement('div');wrap.className='page-frame'+(n===state.activePage?' active':'');wrap.dataset.page=n;wrap.style.width=viewport.width+'px';wrap.style.height=viewport.height+'px';const canvas=document.createElement('canvas');const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';const ctx=canvas.getContext('2d');const transform=dpr!==1?[dpr,0,0,dpr,0,0]:null;await page.render({canvasContext:ctx,viewport,transform}).promise;const layer=document.createElement('div');layer.className='overlay-layer';layer.dataset.page=n;wrap.append(canvas,layer);stage.appendChild(wrap);state.pages[n-1]={page,width:viewport.width,height:viewport.height,wrapper:wrap,layer};wrap.addEventListener('pointerdown',e=>{if(e.target===layer||e.target===canvas){setActivePage(n);selectOverlay(null)}})}}
function setActivePage(n){state.activePage=n;$$('.page-frame').forEach(x=>x.classList.toggle('active',+x.dataset.page===n));updateActivePageLabel()}
function updateActivePageLabel(){$('#activePageLabel').textContent=`${state.activePage} / ${state.pdfjsDoc?.numPages||1}`}
function pushHistory(){state.history.push(JSON.stringify(state.overlays.map(o=>({...o,el:undefined}))));if(state.history.length>30)state.history.shift();updateUndo()}
function updateUndo(){$('#undoBtn').disabled=!state.history.length}
$('#undoBtn').addEventListener('click',()=>{if(!state.history.length)return;const snapshot=JSON.parse(state.history.pop());clearOverlayEls();state.overlays=snapshot;state.overlays.forEach(o=>renderOverlay(o));updateUndo();selectOverlay(null)});
function clearOverlayEls(){$$('.overlay-item').forEach(el=>el.remove())}

$('#addSignature').addEventListener('click',()=>{if(!currentSignature()){openSignatureModal('draw',true);return}addOverlay('signature',{src:currentSignature()})});
$('#addDate').addEventListener('click',()=>{const date=new Intl.DateTimeFormat('ar-SA-u-nu-latn',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());addOverlay('date',{text:date})});
$('#addText').addEventListener('click',()=>{$('#textInput').value='';$('#textModal').classList.remove('hidden');setTimeout(()=>$('#textInput').focus(),80)});
$('#closeText').addEventListener('click',()=>$('#textModal').classList.add('hidden'));
$('#confirmText').addEventListener('click',()=>{const t=$('#textInput').value.trim();if(!t){toast('اكتب النص أولًا');return}$('#textModal').classList.add('hidden');addOverlay('text',{text:t})});
$('#textInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#confirmText').click()});
function addOverlay(type,data){const page=state.pages[state.activePage-1];if(!page)return;pushHistory();let w=type==='signature'?190:type==='date'?145:Math.min(300,Math.max(120,(data.text||'').length*12));let h=type==='signature'?72:42;w=Math.min(w,page.width*.55);const o={id:crypto.randomUUID?.()||('o'+Date.now()+Math.random()),type,page:state.activePage,x:(page.width-w)/2,y:(page.height-h)/2,w,h,...data};state.overlays.push(o);renderOverlay(o);selectOverlay(o.id);toast(type==='signature'?'اسحب التوقيع إلى مكانه':'تمت الإضافة، يمكنك تحريكها')}
function renderOverlay(o){const page=state.pages[o.page-1];if(!page)return;const el=document.createElement('div');el.className='overlay-item';el.dataset.id=o.id;el.style.cssText=`left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px`;if(o.type==='signature')el.innerHTML=`<img src="${o.src}" alt="توقيع"><button class="overlay-delete" type="button" aria-label="حذف">×</button><i class="overlay-handle"></i>`;else el.innerHTML=`<div class="overlay-text">${svgSafeText(o.text)}</div><button class="overlay-delete" type="button" aria-label="حذف">×</button><i class="overlay-handle"></i>`;page.layer.appendChild(el);o.el=el;wireOverlay(o,el)}
function wireOverlay(o,el){el.addEventListener('pointerdown',e=>{if(e.target.classList.contains('overlay-delete')||e.target.classList.contains('overlay-handle'))return;selectOverlay(o.id);setActivePage(o.page);pushHistory();const startX=e.clientX,startY=e.clientY,ox=o.x,oy=o.y;el.setPointerCapture(e.pointerId);const move=ev=>{const r=state.pages[o.page-1].layer.getBoundingClientRect();const nx=ox+(ev.clientX-startX),ny=oy+(ev.clientY-startY);o.x=Math.max(0,Math.min(nx,r.width-o.w));o.y=Math.max(0,Math.min(ny,r.height-o.h));applyOverlay(o)};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)});el.querySelector('.overlay-handle').addEventListener('pointerdown',e=>{e.stopPropagation();selectOverlay(o.id);pushHistory();const handle=e.currentTarget;const sx=e.clientX,sy=e.clientY,ow=o.w,oh=o.h;handle.setPointerCapture(e.pointerId);const move=ev=>{const ratio=o.type==='signature'?ow/oh:null;let nw=Math.max(70,ow-(ev.clientX-sx));let nh=ratio?nw/ratio:Math.max(30,oh+(ev.clientY-sy));const page=state.pages[o.page-1];nw=Math.min(nw,page.width-o.x);nh=Math.min(nh,page.height-o.y);o.w=nw;o.h=nh;applyOverlay(o)};const up=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up)});el.querySelector('.overlay-delete').addEventListener('click',e=>{e.stopPropagation();pushHistory();state.overlays=state.overlays.filter(x=>x.id!==o.id);el.remove();selectOverlay(null)})}
function applyOverlay(o){if(!o.el)return;o.el.style.left=o.x+'px';o.el.style.top=o.y+'px';o.el.style.width=o.w+'px';o.el.style.height=o.h+'px'}
function selectOverlay(id){$$('.overlay-item').forEach(el=>el.classList.toggle('selected',el.dataset.id===id))}

$('#manageSignature').addEventListener('click',()=>openSignatureModal(state.signature?'saved':'draw',false));
$('#closeSignature').addEventListener('click',closeSignatureModal);
$('#signatureModal').addEventListener('pointerdown',e=>{if(e.target===$('#signatureModal'))closeSignatureModal()});
$$('[data-sig-tab]').forEach(btn=>btn.addEventListener('click',()=>switchSigTab(btn.dataset.sigTab)));
function openSignatureModal(tab='saved',addAfter=false){state.pendingAddSignature=addAfter;$('#signatureModal').classList.remove('hidden');switchSigTab(tab);setTimeout(()=>resizeSignatureCanvas(),30)}
function closeSignatureModal(){$('#signatureModal').classList.add('hidden');state.uploadSignature=null;$('#uploadPreviewBox').classList.add('hidden')}
function switchSigTab(tab){$$('[data-sig-tab]').forEach(b=>b.classList.toggle('active',b.dataset.sigTab===tab));$$('[data-sig-pane]').forEach(p=>p.classList.toggle('hidden',p.dataset.sigPane!==tab));$('#saveSignature').dataset.mode=tab;renderSavedSignature();if(tab==='draw')setTimeout(resizeSignatureCanvas,20);updateSaveButton()}
function initSignaturePad(){if(state.signaturePad)return;state.signaturePad=new SignaturePad($('#signatureCanvas'),{minWidth:1.1,maxWidth:2.8,penColor:'#102D43',backgroundColor:'rgba(0,0,0,0)'});state.signaturePad.addEventListener?.('endStroke',updateSaveButton)}
function resizeSignatureCanvas(){initSignaturePad();const c=$('#signatureCanvas');const ratio=Math.max(window.devicePixelRatio||1,1);const rect=c.getBoundingClientRect();if(!rect.width)return;const data=state.signaturePad.isEmpty()?null:state.signaturePad.toData();c.width=rect.width*ratio;c.height=210*ratio;c.getContext('2d').scale(ratio,ratio);if(data)state.signaturePad.fromData(data)}
$('#clearSignature').addEventListener('click',()=>{state.signaturePad?.clear();updateSaveButton()});
$('#signatureUpload').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.uploadSignature=r.result;$('#uploadPreview').src=r.result;$('#uploadPreviewBox').classList.remove('hidden');updateSaveButton()};r.readAsDataURL(f);e.target.value='' });
function updateSaveButton(){const mode=$('#saveSignature').dataset.mode||'saved';let ok=mode==='saved'?!!state.signature:mode==='upload'?!!state.uploadSignature:!!state.signaturePad&&!state.signaturePad.isEmpty();$('#saveSignature').disabled=!ok}
$('#saveSignature').addEventListener('click',()=>{const mode=$('#saveSignature').dataset.mode;let data=mode==='saved'?state.signature:mode==='upload'?state.uploadSignature:state.signaturePad?.toDataURL('image/png');if(!data)return;const shouldAdd=state.pendingAddSignature;state.signature=data;try{localStorage.setItem(SIG_KEY,data)}catch(e){toast('تعذر حفظ التوقيع محليًا، سيبقى لهذه الجلسة فقط')}updateSignatureUi();closeSignatureModal();state.pendingAddSignature=false;toast('تم حفظ التوقيع');if(shouldAdd&&state.pdfjsDoc)addOverlay('signature',{src:data})});
$('#deleteSavedSignature').addEventListener('click',()=>{state.signature=null;try{localStorage.removeItem(SIG_KEY)}catch(e){}updateSignatureUi();switchSigTab('draw');toast('تم حذف التوقيع المحفوظ')});

async function textToPng(text,width,height){await document.fonts.ready;const scale=2;const c=document.createElement('canvas');c.width=Math.ceil(width*scale);c.height=Math.ceil(height*scale);const ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.clearRect(0,0,width,height);ctx.fillStyle='#172A38';ctx.textAlign='center';ctx.textBaseline='middle';ctx.direction='rtl';ctx.font=`600 ${Math.max(13,Math.min(24,height*.48))}px NaifCraft, Tahoma, Arial`;ctx.fillText(text,width/2,height/2,width-8);return c.toDataURL('image/png')}
async function createSignedPdf(){if(!state.originalBytes)return;if(!state.overlays.length){toast('أضف التوقيع أو عنصرًا إلى المستند أولًا');return}loading(true,'جاري تثبيت العناصر داخل PDF…');try{const pdfDoc=await PDFLib.PDFDocument.load(state.originalBytes.slice(),{ignoreEncryption:false});const pages=pdfDoc.getPages();for(const o of state.overlays){const p=pages[o.page-1];if(!p)continue;const meta=state.pages[o.page-1];const pw=p.getWidth(),ph=p.getHeight();const x=o.x/meta.width*pw,y=ph-((o.y+o.h)/meta.height*ph),w=o.w/meta.width*pw,h=o.h/meta.height*ph;let src=o.src;if(o.type!=='signature')src=await textToPng(o.text,o.w,o.h);let img;if(/^data:image\/jpe?g/i.test(src))img=await pdfDoc.embedJpg(src);else img=await pdfDoc.embedPng(src);p.drawImage(img,{x,y,width:w,height:h})}const out=await pdfDoc.save();state.outputBlob=new Blob([out],{type:'application/pdf'});state.outputFile=new File([state.outputBlob],outputName(),{type:'application/pdf'});$('#resultName').textContent=state.outputFile.name;$('#resultInfo').textContent=formatBytes(state.outputFile.size);$('#resultPanel').classList.remove('hidden');$('#workspace').classList.add('hidden');setStep(3);$('#resultPanel').scrollIntoView({behavior:'smooth',block:'center'});toast('تم إنشاء الملف الموقع')}catch(err){console.error(err);toast('تعذر إنشاء الملف. قد يكون PDF محميًا ضد التعديل.')}finally{loading(false)}}
$('#exportPdf').addEventListener('click',createSignedPdf);
$('#shareResult').addEventListener('click',shareOutput);$('#downloadResult').addEventListener('click',downloadOutput);
$('#backToEdit').addEventListener('click',()=>{$('#resultPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');setStep(2);$('#workspace').scrollIntoView({behavior:'smooth',block:'start'})});
async function shareOutput(){if(!state.outputFile){await createSignedPdf();if(!state.outputFile)return}try{if(navigator.canShare?.({files:[state.outputFile]})&&navigator.share){await navigator.share({files:[state.outputFile],title:'ملف موقع'})}else{downloadOutput();toast('تم تنزيل الملف. أرفقه في واتساب أو البريد.')}}catch(err){if(err?.name!=='AbortError'){downloadOutput();toast('تم تنزيل الملف بدل المشاركة')}}}
function downloadOutput(){if(!state.outputBlob)return;const url=URL.createObjectURL(state.outputBlob);const a=document.createElement('a');a.href=url;a.download=outputName();document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500)}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#signatureModal').classList.add('hidden');$('#textModal').classList.add('hidden')}});
loadSavedSignature();
